spring:
    datasource:
        #name: testdn
        url: jdbc:mysql://localhost:3306/testdb
        username: root
        password: root
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.ecnu.model  
  #mapperLocations: classpath:mapper/*.xml
  
